include: /risk1/chengxilong/sentiment-analysis-on-movie-reviews/cfg/base.yaml
model_path: "/risk1/chengxilong/sentiment-analysis-on-movie-reviews/weights/xlnet-base-cased"
tokenizer: "xlnet-base-cased"
pad_token: "[PAD]"
num_train_epochs: 10
per_device_train_batch_size: 256
per_device_eval_batch_size: 256
warmup_steps: 100
learning_rate: 2e-4
max_length: 30

